# Generated by Django 4.0.3 on 2022-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('AST', 'Atlantic Standard Time'), ('EST', 'Eastern Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('PST', 'Pacific Standard Time'), ('AKST', 'Alaska Standard Time'), ('HST', 'Hawaii Standard Time'), ('SST', 'Samoa Standard Time')], default='CST', max_length=4),
        ),
    ]
