# Generated by Django 4.0.3 on 2022-05-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='markdown_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='markdown_url',
            field=models.URLField(default='https://www.github.com/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
