# Generated by Django 4.0.3 on 2022-05-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='default_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='default_users', to='auth.group'),
            preserve_default=False,
        ),
    ]
