# Generated by Django 4.0.3 on 2022-05-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lesson_group_remove_topic_img_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicLink',
            new_name='LessonLink',
        ),
    ]
