# Generated by Django 4.0.3 on 2022-05-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_checkin_group_user_default_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_users', to='auth.group'),
        ),
    ]
