# Generated by Django 4.0.3 on 2022-05-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_alter_user_default_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.group')),
                ('github_key', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
