# Generated by Django 4.0.3 on 2022-05-01 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_topiclink_lessonlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ManyToManyField(related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
