# Generated by Django 4.0.3 on 2022-05-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_activity_date'),
        ('app', '0003_forum_forumimage_forumpost_forumcomment'),
    ]

    operations = [
    ]
