# Generated by Django 4.0.3 on 2022-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20220507_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='forum_posts', to='app.forumimage'),
        ),
    ]
