# Generated by Django 4.0.3 on 2022-05-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_forumpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='app.forumpost'),
            preserve_default=False,
        ),
    ]
