# Generated by Django 4.0.3 on 2022-05-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_lesson_markdown_url_lesson_lesson_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='markdown',
            field=models.TextField(default=' '),
        ),
    ]
