# Generated by Django 4.0.3 on 2022-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_forumcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='forum_posts', to='app.forumimage'),
        ),
    ]
