# Generated by Django 4.0.3 on 2022-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lesson_title_alter_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonlink',
            name='topic',
        ),
        migrations.AddField(
            model_name='lessonlink',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='app.lesson'),
            preserve_default=False,
        ),
    ]
