# Generated by Django 4.0.3 on 2022-05-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_lessonlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlink',
            name='originator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
