# Generated by Django 4.0.3 on 2022-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_lessonlink_topic_lessonlink_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlink',
            name='link_type',
            field=models.IntegerField(choices=[(0, 'Supplement'), (1, 'Challenge'), (2, 'Assessment')], default=1),
        ),
    ]
