# Generated by Django 4.0.3 on 2022-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitygroup',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
