# Generated by Django 4.0.3 on 2022-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default={'group_team': '', 'interview_date': '', 'interviewer': '', 'mentor': '', 'resume_coach': ''}, null=True),
        ),
    ]
