# Generated by Django 4.0.3 on 2022-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
