# Generated by Django 4.0.3 on 2022-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_topic_parent_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent_topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='sub_topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_topics', to='app.topic'),
        ),
    ]
