# Generated by Django 4.0.3 on 2022-05-05 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 15, 24, 12, 532677, tzinfo=utc)),
        ),
    ]
