# Generated by Django 4.0.3 on 2022-05-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_questionresponse_question_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='questionresponse',
            old_name='text',
            new_name='response_text',
        ),
    ]
