# Generated by Django 4.0.3 on 2022-05-05 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_activity_size_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygroup',
            name='group_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 15, 52, 42, 811361, tzinfo=utc)),
        ),
    ]
