# Generated by Django 4.0.3 on 2022-05-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_text_questionoption_question_text_and_more'),
        ('app', '0018_alter_activity_date'),
    ]

    operations = [
    ]
